"""Merge translated batches into data/scopes_ko.json and check them against the English texts.

    NEBIUS_API_KEY= TAVILY_API_KEY= .venv/Scripts/python.exe -X utf8 scripts/merge_scope_translations.py --built 2026-10-03
    ... --batches "data/translate_work/ko_batch_*.json"   # the default
    ... --partial                                          # work in progress: allow missing ids

How data/scopes_ko.json is made (format and display rules: regnav/ko_scopes.py):

 1. scripts/export_scopes_for_translation.py lists every English text a Korean report can quote, with its
    SHA-256 (data/translate_work/sources.json; this script rebuilds the same list in memory).
 2. A translator (so far Claude, in batches of about 20 texts, each batch reviewed by a second pass) writes
    data/translate_work/ko_batch_NN.json = {"<id>": {"src_sha256": "<hash from step 1, unchanged>", "ko": "<Korean>"}}.
    data/translate_work/ is git-ignored work space: everything in it is either regenerated by step 1 or
    ends up in data/scopes_ko.json.
 3. This script overlays the batches on the current data/scopes_ko.json (a batch entry replaces the entry
    with the same id, so after a snapshot rebuild only the texts whose hash changed need translating),
    runs ``problems`` and writes data/scopes_ko.json only when nothing is wrong. scripts/test_dryrun.py
    runs the same ``problems`` on the committed file.

Offline and free: it reads the committed snapshots and the batch files, nothing else.
"""
from __future__ import annotations

import argparse
import collections
import glob
import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

import export_scopes_for_translation as export  # noqa: E402
from regnav import ko_scopes  # noqa: E402
from regnav.sources import ecfr, unece  # noqa: E402

NOTE = ("비공식 참고 번역 (Claude), 원문 우선. Unofficial Korean reference translations (machine translation by "
        "Claude; each batch was checked by a second Claude pass, with no review by a human or a legal "
        "translator) of the regulation Scope texts RegNav quotes in Korean mode. The English original is what "
        "counts. texts maps an id (listed by scripts/export_scopes_for_translation.py, see regnav/ko_scopes.py) "
        "to {src_sha256: SHA-256 of the English text that was translated, ko: the Korean text}; a translation "
        "is shown only when its hash matches the text being quoted, so a changed text gets a note instead of an "
        "out-of-date translation. FMVSS excerpts that stop at the 1,500-character cap end mid-sentence: the "
        "Korean stops at the same place and the report adds ' [...]' to both. Rebuild with "
        "scripts/merge_scope_translations.py.")

NUMBER = re.compile(r"[0-9]+(?:[.,][0-9]+)*")  # 4,536  1.1  2.43.1  1949  25
# vehicle categories (M1, N2, O3, L5, C1, M1G), regulation and paragraph labels (R13-H, S3, FAD1, J944)
CODE = re.compile(r"(?<![A-Za-z0-9])[A-Z][A-Za-z]{0,3}[0-9]+[A-Za-z]*(?:-[A-Z0-9]+)*(?![A-Za-z0-9])")
HANGUL = re.compile(r"[가-힣]")
RATIO = (0.25, 1.5)  # len(ko) / len(en): the real texts are 0.36 to 0.78; outside means dropped or pasted text


def numbers(text: str) -> collections.Counter:
    return collections.Counter(NUMBER.findall(text))


def codes(text: str) -> collections.Counter:
    return collections.Counter(CODE.findall(text))


def problems(sources: list[dict], texts: dict, partial: bool = False) -> list[str]:
    """Everything wrong with a translation table, as one line per problem (empty list: fine).

    Per English text: a translation exists (unless ``partial``), it was made from exactly this text (hash),
    it is not empty, it contains Hangul and no "[...]" (the report adds the cut marker itself), it has one
    line per English line, a plausible length, and every number and every category or section code of the
    English appears in the Korean at least as often (a dropped "4,536" or "M1" is a changed scope)."""
    out: list[str] = []
    known = {e["id"] for e in sources}
    out += [f"{i}: not the id of any quotable text" for i in texts if i not in known]
    for e in sources:
        i, en = e["id"], e["src"]
        entry = texts.get(i)
        if entry is None:
            if not partial:
                out.append(f"{i}: no translation")
            continue
        if not isinstance(entry, dict) or set(entry) != {"src_sha256", "ko"} or not isinstance(entry["ko"], str):
            out.append(f"{i}: entry must be {{src_sha256, ko}} with a string ko")
            continue
        ko = entry["ko"]
        if entry["src_sha256"] != ko_scopes.digest(en):
            out.append(f"{i}: translated from another version of the English text (hash differs): retranslate")
        if not ko.strip():
            out.append(f"{i}: empty translation")
            continue
        if ko != ko.strip():
            out.append(f"{i}: leading or trailing whitespace")
        if not HANGUL.search(ko):
            out.append(f"{i}: no Hangul")
        if "[...]" in ko:
            out.append(f"{i}: contains the [...] cut marker, which the report adds itself")
        if len(ko.split("\n")) != len(en.split("\n")):
            out.append(f"{i}: {len(ko.split(chr(10)))} Korean lines for {len(en.split(chr(10)))} English lines")
        if not RATIO[0] <= len(ko) / len(en) <= RATIO[1]:
            out.append(f"{i}: Korean/English length ratio {len(ko) / len(en):.2f} outside {RATIO}")
        for label, find in (("number", numbers), ("code", codes)):
            lost = find(en) - find(ko)
            if lost:
                out.append(f"{i}: {label}(s) of the English missing in the Korean: {sorted(lost.elements())}")
    return out


def load_batches(pattern: str) -> dict:
    """{id: entry} from every file matching ``pattern`` (relative to the repo root); an id in two files is an error."""
    merged: dict = {}
    files = sorted(glob.glob(str(ROOT / pattern)))
    if not files:
        sys.exit(f"no batch files match {pattern}")
    for name in files:
        batch = json.loads(Path(name).read_text(encoding="utf-8"))
        again = sorted(set(batch) & set(merged))
        if again:
            sys.exit(f"{Path(name).name}: ids already in an earlier batch: {again}")
        merged.update(batch)
        print(f"  {Path(name).name}: {len(batch)} texts")
    return merged


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--built", default=date.today().isoformat(), help="date recorded in the file (YYYY-MM-DD)")
    parser.add_argument("--batches", default="data/translate_work/ko_batch_*.json")
    parser.add_argument("--partial", action="store_true", help="allow ids without a translation")
    args = parser.parse_args()
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", args.built):
        sys.exit("--built must be YYYY-MM-DD")

    sources = export.build_sources()
    known = {e["id"] for e in sources}
    current = dict(ko_scopes.texts())
    gone = sorted(set(current) - known)
    if gone:
        print(f"dropping {len(gone)} existing entries whose id is no longer exported: {gone}")
        current = {i: t for i, t in current.items() if i in known}
    batches = load_batches(args.batches)
    table = {**current, **batches}
    ordered = {e["id"]: table[e["id"]] for e in sources if e["id"] in table}

    found = problems(sources, ordered, args.partial)
    if found:
        sys.exit(f"{len(found)} problem(s), nothing written:\n- " + "\n- ".join(found))

    data = {
        "note": NOTE,
        "built": args.built,
        "translator": "Claude (Anthropic)",
        "sources": {
            "un_scope": f"data/unece_scopes.json, built {unece.scopes().get('built')} (EU Official Journal copies)",
            "fmvss_scope": f"data/ecfr_snapshot.json, dated {ecfr.snapshot().get('date')} (49 CFR 571, eCFR)",
            "un_summary": "regnav/sources/unece.py catalogue (RegNav's own one-line summaries, not official text)",
        },
        "texts": ordered,
    }
    with open(ko_scopes.PATH, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write("\n")
    kinds = {e["id"]: e["kind"] for e in sources}
    print(f"wrote {ko_scopes.PATH}: {len(ordered)}/{len(sources)} texts, "
          f"{sum(len(t['ko']) for t in ordered.values())} Korean characters for "
          f"{sum(e['chars'] for e in sources if e['id'] in ordered)} English characters")
    for kind in ko_scopes.KINDS:
        ids = [i for i in ordered if kinds[i] == kind]
        print(f"  {kind}: {len(ids)} texts, {sum(len(ordered[i]['ko']) for i in ids)} Korean characters")


if __name__ == "__main__":
    main()
